# Generated by Django 3.0 on 2022-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_match_live_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
