# Generated by Django 3.0 on 2022-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_match_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_result',
            field=models.CharField(default='0-0', max_length=100),
        ),
    ]
