# Generated by Django 3.0 on 2022-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220704_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_result',
            field=models.CharField(default='draw', max_length=100),
        ),
    ]
