# Generated by Django 3.0 on 2022-07-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220704_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
