# Generated by Django 3.0 on 2022-07-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_player_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='updated_at',
        ),
    ]
