# Generated by Django 3.0 on 2022-07-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220704_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='match',
        ),
        migrations.AddField(
            model_name='player',
            name='main_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Team'),
        ),
    ]
