# Generated by Django 3.0 on 2022-07-05 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerPerMatch',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
    ]
